name: hello-world

# on: push
on:
  workflow_dispatch: # manual

jobs:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
